on: release
name: Build
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Pull dependencies
        run: go get ./...
      - name: Build linux/386
        env:
          GOARCH: "386"
          GOOS: linux
        run: go build ./... -o breeze-linux-386
      - name: Build linux/amd64
        env:
          GOARCH: amd64
          GOOS: linux
        run: go build ./... -o breeze-linux-amd64
      - name: Build darwin/386
        env:
          GOARCH: "386"
          GOOS: darwin
        run: go build ./... -o breeze-darwin-386
      - name: Build darwin/amd64
        env:
          GOARCH: amd64
          GOOS: darwin
        run: go build ./... -o breeze-darwin-amd64
