on: release
name: Build
jobs:
  release-linux-386:
    name: release linux/386
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Pull dependencies
        run: go get ./...
      - name: Build linux/386
        env:
          GOARCH: "386"
          GOOS: linux
          CGO_ENABLED: "0"
        run: go build -ldflags="-w -s" -o breeze-linux-386
      - name: Upload binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./breeze-linux-386
          asset_name: ./breeze-linux-386
          asset_content_type: application/octet-stream
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Pull dependencies
        run: go get ./...
      - name: Build linux/amd64
        env:
          GOARCH: "amd64"
          GOOS: linux
          CGO_ENABLED: "0"
        run: go build -ldflags="-w -s" -o breeze-linux-amd64
      - name: Upload binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./breeze-linux-amd64
          asset_name: ./breeze-linux-amd64
          asset_content_type: application/octet-stream
  release-darwin-386:
    name: release darwin/386
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Pull dependencies
        run: go get ./...
      - name: Build darwin/386
        env:
          GOARCH: "386"
          GOOS: darwin
          CGO_ENABLED: "0"
        run: go build -ldflags="-w -s" -o breeze-darwin-386
      - name: Upload binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./breeze-darwin-386
          asset_name: ./breeze-darwin-386
          asset_content_type: application/octet-stream
  release-darwin-amd64:
    name: release darwin/386
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Pull dependencies
        run: go get ./...
      - name: Build darwin/amd64
        env:
          GOARCH: "amd64"
          GOOS: darwin
          CGO_ENABLED: "0"
        run: go build -ldflags="-w -s" -o breeze-darwin-amd64
      - name: Upload binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./breeze-darwin-amd64
          asset_name: ./breeze-darwin-amd64
          asset_content_type: application/octet-stream
